### ISSUE TITLE
使用lstg.world的值代替固定值

### ISSUE THREAD

**Issue by Xrysnow** [Xiliusha/LuaSTG-LuaData#2]
https://github.com/Xiliusha/LuaSTG-LuaData/blob/2e79392a5feb4baaaac8b6267e692220455e987d/game/Thlib/bullet/bullet.lua#L162
https://github.com/Xiliusha/LuaSTG-LuaData/blob/2e79392a5feb4baaaac8b6267e692220455e987d/game/Thlib/player/reimu/reimu.lua#L152
https://github.com/Xiliusha/LuaSTG-LuaData/blob/2e79392a5feb4baaaac8b6267e692220455e987d/game/Thlib/player/reimu/reimu.lua#L172-L175
https://github.com/Xiliusha/LuaSTG-LuaData/blob/2e79392a5feb4baaaac8b6267e692220455e987d/game/Thlib/enemy/boss.lua#L153

**Comment by Xrysnow** [comment]
https://github.com/Xiliusha/LuaSTG-LuaData/blob/119fbbec5ff9d04451b74e0d1836996a6f5ad446/game/Thlib/enemy/boss.lua#L1090-L1091
https://github.com/Xiliusha/LuaSTG-LuaData/blob/119fbbec5ff9d04451b74e0d1836996a6f5ad446/game/Thlib/BulletEx.lua#L103-L106

**Comment by Xiliusha** [comment]
ojbk
